name: MAUI Android Workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - run: dotnet workload restore
      - run: dotnet restore
      - run: dotnet build -f net8.0-android -c Release
      - run: dotnet test -c Release --no-restore --no-build --verbosity normal
