name: MAUI Android Workflow

on:
  push:
    branches:
      - main
      - develop
      - release/**
      - feature/**
  pull_request:
    branches:
      - main
      - develop
      - release/**
      - feature/**

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - run: dotnet workload restore android
      - run: dotnet restore -f net8.0-android
      - run: dotnet build -f net8.0-android -c Release
      - run: dotnet test -c Release --no-restore --no-build --verbosity normal
